### ISSUE TITLE
Expected behavior of "previous 6 Sessions" output

### ISSUE THREAD

**Issue by aperture-sandi** [turboflakes/scouty#2]
Making good use of scouty, thanks!  
It appears that "Number of Para Validator times in previous 6 Sessions" and "Number of Authored blocks in previous 6 Sessions" only outputs accurate data if scouty has been running for at least 6 sessions.  Is this the expected behavior?
For example if scouty is initialized a few minutes before a new session, the new_session hook "Number of Authored blocks in previous 6 Sessions" will return ONLY the number of blocks authored in the previous session not the previous 6 sessions.

**Comment by paulormart** [comment]
Hi,

Yes its working as expected. The reason, is because, all that data is not available directly from on-chain storage, only the authored blocks from the current session are easily available, which means that all this information is just being kept in memory when the bot is running. 

Perhaps we could get initially the authored blocks from previous sessions by reading all blocks since the last 6 sessions... but the bot currently doesn't do that.

A workaround could be just to persist this data in a local file and load it when it starts.. but if the bot stays off for a while this info may no longer be reliable.. 

I didn't wanted to complicate it too much in the beginning so i just left it as it is now.

**Comment by aperture-sandi** [comment]
Got it, thanks!  I am writing data to a log so it should be easy enough to calculate from log data.
